codemods:
  only:
    - sonar:python/break-or-continue-out-of-loop-S1716
    - sonar:python/disable-graphql-introspection-S6786
    - sonar:python/django-json-response-type-S5131
    - sonar:python/django-model-without-dunder-str-S6554
    - sonar:python/django-receiver-on-top-S6552
    - sonar:python/enable-jinja2-autoescape-S5247
    - sonar:python/exception-without-raise-S3984
    - sonar:python/fix-assert-tuple-S5905
    - sonar:python/fix-float-equality-S1244
    - sonar:python/fix-math-isclose-S6727
    - sonar:python/fix-missing-self-or-cls-S5719
    - sonar:python/flask-json-response-type-S5131
    - sonar:python/jwt-decode-verify-S5659
    - sonar:python/literal-or-new-object-identity-S5796
    - sonar:python/numpy-nan-equality-S6725
    - sonar:python/remove-assertion-in-pytest-raises-S5915
    - sonar:python/secure-random-S2245
    - sonar:python/secure-tempfile-S5445
    - sonar:python/sql-parameterization-S3649
    - sonar:python/url-sandbox-S5144
